function [redraw, rekey, undoable] = WriteFeatureDateFile(iClust)

% WriteFeatureDateFile(iClust)
%
% WriteFeatureDate for a single cluster
% 
% INPUTS
%    iClust
%
% OUTPUTS
%
% NONE
% TO USE WITH MCLUST, put this in the MClust/ClusterOptions folder

% ADR 2011

redraw = false; rekey = false; undoable = true;

global MClust_Directory MClust_FeatureNames

WriteFDClustDataFigure = figure('Name','Feature Data to Write','Units', 'Normalized', 'UserData', iClust, 'Tag', 'WriteFeatureData');
%-------------------------------
% Alignment variables

uicHeight = 0.04;
uicWidth  = 0.25;
dX = 0.3;
XLocs = 0.1:dX:0.9;
dY = 0.04;
YLocs = 0.9:-dY:0.0;
FrameBorder = 0.01;

% Create Feature Listboxes
uicontrol('Parent', WriteFDClustDataFigure,...
	'Style', 'text', 'String', 'FEATURES', 'Units', 'Normalized', 'Position', [XLocs(1) YLocs(4) 2*uicWidth uicHeight]);
uicontrol('Parent', WriteFDClustDataFigure,...
	'Style', 'text', 'String', 'Available', 'Units', 'Normalized', 'Position', [XLocs(1) YLocs(5) uicWidth uicHeight]);
ui_featuresIgnoreLB =  uicontrol('Parent', WriteFDClustDataFigure,...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(17) uicWidth 12*uicHeight],...
	'Style', 'listbox', 'Tag', 'FeaturesIgnoreListbox',...
	'Callback', 'TransferBetweenListboxes',...
	'HorizontalAlignment', 'right', ...
	'Enable','on', ...
	'String', MClust_FeatureNames, ...
	'TooltipString', 'These are features which are not included but are also available.');
uicontrol('Parent',WriteFDClustDataFigure,...
	'Style', 'text', 'String', 'Use', 'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth YLocs(5) uicWidth uicHeight]);
ui_featuresUseLB = uicontrol('Parent', WriteFDClustDataFigure,...
	'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth YLocs(17) uicWidth 12*uicHeight],...
	'Style', 'listbox', 'Tag', 'FeaturesUseListbox',...
	'Callback', 'TransferBetweenListboxes',...
	'HorizontalAlignment', 'right', ...
	'Enable','on', ...
	'TooltipString', 'These features will be written out.');

set(ui_featuresIgnoreLB, 'UserData', ui_featuresUseLB);
set(ui_featuresUseLB,    'UserData', ui_featuresIgnoreLB);

uicontrol('Parent',WriteFDClustDataFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) + uicWidth/2 YLocs(1) uicWidth/2 uicHeight], ...
	'Style', 'text','Tag', 'RunKlustaKwikiClust', 'String', num2str(iClust), ...
	'TooltipString', 'Cluster 1');	

uicontrol('Parent',WriteFDClustDataFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(1) uicWidth/2 uicHeight], ...
	'Style', 'text','String', 'Cluster');	

uicontrol('Parent',WriteFDClustDataFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1) YLocs(22) uicWidth uicHeight*2], ...
	'Style', 'pushbutton','Tag', 'AcceptFeatures_FBS', 'String', 'GO', 'Callback', 'WriteFDClustCallbacks', ...
	'TooltipString', 'Accept features to write');
uicontrol('Parent',WriteFDClustDataFigure, ...
	'Units', 'Normalized', 'Position', [XLocs(1)+uicWidth YLocs(22) uicWidth uicHeight*2], ...
	'Style', 'pushbutton', 'String', 'CANCEL', 'Callback', 'close');